### ISSUE TITLE
Projection has no attribute 'label'

### ISSUE THREAD

**Issue by apdavison** [SpiNNakerManchester/sPyNNaker8#100]
This is for the current NMPI version, but as far as I can see, it is not defined in the master branch either.

**Comment by apdavison** [comment]
It is also missing the "pre" (reference to pre-synaptic Population) and "post" attributes.

**Comment by alan-stokes** [comment]
yep, we're missing those 3 property calls. 

working on a branch for it now

**Comment by alan-stokes** [comment]
fixed in prs

https://github.com/SpiNNakerManchester/sPyNNaker/pull/454
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/101

**Comment by alan-stokes** [comment]
worth noting that pynn 0.75 interface doesn't support these calls from the API defined here:
https://neuralensemble.org/docs/PyNN/0.7/api/api-0.7.html

thus why its in spynnaker8 and not spynnaker

**Comment by apdavison** [comment]
Thanks for pointing that out. This is a problem with the PyNN 0.7 docs. These attributes have been in PyNN since version 0.1 I believe.

**Comment by alan-stokes** [comment]
*insert grumble here* ah well. Given we plan to discontinue pynn 0.75 in the next few releases, i'm not too fussed about pushing these things into spynnaker to support pynn 0.75. If critcle, i'll move them over.
