### ISSUE TITLE
"ImportError: No module named pynn" when running `import pynn.spiNNaker as sim` on Ubuntu 16.04

### ISSUE THREAD

**Issue by iamlucaswolf** [SpiNNakerManchester/sPyNNaker8#104]
Hi,

I am currently trying to install sPyNNaker8 inside a Python 2.7.12 virtualenv on Ubuntu 16.04. To that end, I performed every step as outlined in [the tutorial](http://spinnakermanchester.github.io/spynnaker/4.0.0/PyNNOnSpinnakerInstall.html). The installation, including the `python -m spynnaker8.setup-pynn` step succeeded without any errors.

Strangely, when I try to configure the installation by running `import pynn.spiNNaker as sim` inside a Python shell, I get an error saying `ImportError: No module named pynn`.  However, `pip search pynn` lists PyNN (0.9.2), sPyNNaker (1!4.0.0) and sPyNNaker8 (1!4.0.0) as installed. (Regarding PyNN: Originally, the installation procedure installed an older version of PyNN, 0.8.3 or so. I upgraded it via pip, but it didn't resolve the problem)

Is this a bug? Or did I mess something up during the installation?
Any help is appreciated.

Thanks,
Lucas

**Comment by rowleya** [comment]
Did you upgrade PyNN after running ```spynnaker8.setup-pynn```?  If so, it is possible that it has removed the spynnaker install part from PyNN, in which case running it again might help.

Note that it is also possible to simply use ```import spynnaker8 as sim```, which should work in a similar way.

**Comment by iamlucaswolf** [comment]
I just checked and it worked by using `import spynnaker8 as sim` as you suggested. Thanks a lot! 

One smaller thing though: `sim.end()` as described in the tutorial (with `sim` being the `spynnaker` package) throws an `AttributeError: 'Spynnaker8FailedState' object has no attribute 'write_on_end'`.

To double-check I created another clean virtualenv and went through the motions once more, this time without upgrading PyNN. The original problem persisted, but your fix worked. 

Might I ask whether this (ie. using `spynnaker8.setup()`) is the way it's supposed to be done? If so, I would be willing to update the tutorial accordingly.

**Comment by rowleya** [comment]
The normal operation is:
```
import pyNN.spiNNaker as sim

sim.setup()

# Create populations and projections
...

sim.end()
```

I am unsure why you are not able to use ```pyNN.spiNNaker```; this might indicate another pyNN install somewhere in your python path.

The attribute error you are seeing could indicate that you haven't called sim.setup first?

**Comment by 366anna** [comment]
I had similar odd behaviour because I didn't update neo package together with pyNN.

**Comment by rowleya** [comment]
Ahh interesting - thanks!

**Comment by iamlucaswolf** [comment]
Just ran `pip install --upgrade neo`, issue persists.

**Comment by andrewgait** [comment]
Hi Lucas, I think that it's case sensitive, so you need to do `import pyNN` or `import pyNN.spiNNaker` - I just tried `import pynn` on my virtualenv and it failed too...

**Comment by iamlucaswolf** [comment]
Thank you so much, @andrewgait, that was it.
I will mark this issue as closed. However, might I suggest changing the tutorial (http://spinnakermanchester.github.io/spynnaker/4.0.0/PyNNOnSpinnakerInstall.html) accordingly?

**Comment by andrewgait** [comment]
Done - thanks for spotting it.
