### ISSUE TITLE
Unable to initilize "v" with  p.RandomDistribution if only one neuron in Population

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#13]
numpy array length 1 instead of number error when initialize is called  with p.RandomDistribution on a population of size 1

Script:
import spynnaker8 as p
from spynnaker8 import IF_curr_exp
CELL_PARAMS_LIF = {'cm': 0.25, 'i_offset': 0.0, 'tau_m': 20.0,
                   'tau_refrac': 2.0, 'tau_syn_E': 5.0, 'tau_syn_I': 5.0,
                   'v_reset': -70.0, 'v_rest': -65.0, 'v_thresh': -50.0}
p.setup(timestep=1, min_delay=1.0, max_delay=144)
pop = p.Population(1, IF_curr_exp(**CELL_PARAMS_LIF), label='pop_1')
rng = p.NumpyRNG(seed=28375)
v_init = p.RandomDistribution('uniform', [-60, -40], rng)
pop.initialize("v", v_init)
p.run(500)

Does not happen in PyNN 7
Does not happen if a constant is passed into pop.initialize

**Comment by Christian-B** [comment]
A hack which get around this issue is:
Change line 1315 in DataSpecification/data_specification/data_specification_generator.py
from:
            data_value = decimal.Decimal("{}".format(data)) * data_type.scale

to:

        if isinstance(data, numpy.ndarray) and len(data) == 1:
            data_value = decimal.Decimal("{}".format(data[0])) * data_type.scale
        else:
            data_value = decimal.Decimal("{}".format(data)) * data_type.scale

**Comment by alan-stokes** [comment]
funny that you call it a hack, we call it working with numpy. that's basically what we do everywhere else. Doing it within the DSG is not the place to do it, the place to do it is during data input.

**Comment by alan-stokes** [comment]
fixed https://github.com/SpiNNakerManchester/sPyNNaker/pull/323

**Comment by Christian-B** [comment]
I think this one is fixed!

**Comment by Christian-B** [comment]
tested by sPyNNaker7/p7_integration_tests/test_0_1_time_steps/test_single_neuron_tests/test_a_single_if_cur_exp_neuron.py

and
 sPyNNaker8/p8_integration_tests/test_0_1_time_steps/test_single_neuron_tests/test_a_single_if_cur_exp_neuron.py

**Comment by alan-stokes** [comment]
well given the merge is done, id close the issue.
