### ISSUE TITLE
unable to perform repeated runs of variable length

### ISSUE THREAD

**Issue by rjames91** [SpiNNakerManchester/sPyNNaker8#131]
When running the following code:
sim.run(10)
for i in range(10):
    sim.run(1000.)
sim.end()

The simulator will run repeatedly for durations of 10ms instead of 1s.

This issue emerges when I attempt to run a simulation with STDP for a very short amount of time initially (10ms) to obtain connection weights that approximate startup conditions, then subsequent runs should be for longer periods of time before reading of connection weight values again.

I have tried this with run_until and run_for and get the same outcome.

**Comment by Christian-B** [comment]
This is a known issues as when the first run which is only 10 is seen. Enough space is created on the machine for exactly 10 timesteps.

If you then run it for longer it has to split into many short runs.
Two bits of good news.
1. It appears you can get the initial weights without a short run. (@rowleya )
2. My next todo is to address the auto puase resume to fix this saving exactly the right amount.

**Comment by rowleya** [comment]
To get initial weights, you should be able to call get("weights") before a call to run (and if you can't this is a different bug).  The thing to note here is that the object returned is then a proxy; this will be filled in during the run call.  So you can't actually read it until after run!  As an example, you can do this:
```
sim.setup(1.0)
...
proj = sim.Projection(...)
weights = proj.get("weights")
# You can't read the returned "weights" object until *after* run
...
p.run(...)
new_weights = proj.get("weights")

# Run has been called, so it is now safe to read the weights
print(weights)
print(new_weights)
```

**Comment by rjames91** [comment]
I've just tried this method and it works great, I think I'd attempted something similar in the past but had checked the weights variable before calling run. Thanks for the tip!

**Comment by alan-stokes** [comment]
given the pr is merged. closing, if its still a issue. reopen
