### ISSUE TITLE
TestMultiBoardSpikeOutput hangs in python3

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#136]
regarding:
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/test_various/test_multiboard_spike_output.py
Edit: Python 3.6 only

EDIT: red herring: 
yes I know that with 48 * 2 + 1 chips required this test should not work on a spin three board that 72 chips which is less than the 97 requested,

Yet this script does not go pop.
EDIT: end Red herring

EDIT: lowering n_chips_required to one and it still hangs. 

Instead it hangs on the run stage.

**Comment by Christian-B** [comment]
It gets as far as ApplicationRunner before hanging.

That said all the reports which appear to run produce no output so something has meesed up well before that.

**Comment by Christian-B** [comment]
Even weirder!

Using python 2.7 the script runs.

In python 3.6 it hangs!

**Comment by Christian-B** [comment]
One problem is that the n_chips_required is ignored.

https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/322

But that does not explain why the python3.6 stuff fails.!

**Comment by Christian-B** [comment]
In this particular test all n_chips_required was doing is asking spalloc to allocate three board so there where 3 ethernet_connected_chips and adding pops to just those.

So with https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/322 there was just one pop added and the rest should have run.

So the hanging is NOT caused by there not being enough chips available but some other python3 monster!

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/test_various/test_spike_io_multi_run.py also hangs.

interesting how both that hang have io stuff in them.

**Comment by Christian-B** [comment]
Also hangs on spalloc

**Comment by Christian-B** [comment]
spinnaker_graph_front_end.examples.test_retransmission_phase_on_multi_cores.main also appears to hang

**Comment by dkfellows** [comment]
The problem is (probably) the interaction of the threads used in various connection implementations with the processes forked off by the multiprocessing module. The difference between 2.7 and 3.6 is in what locks are held at the point when the internal `fork()` call happens (it's _really_ hard to predict what's going on there) but this is a class of problem I've seen (once!) even without any Python at all. It was also deeply horrible.

**Comment by Christian-B** [comment]
Appears to also effect **https://github.com/SpiNNakerManchester/sPyNNaker8/tree/master/p8_integration_tests/test_live_packet_gather**

**Comment by Christian-B** [comment]
All tests appear to run in Jemkins so assumed fixed
