### ISSUE TITLE
population.set() not working

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#14]
set method in population not working

test script:

import spynnaker8 as p
CELL_PARAMS_LIF = {'cm': 0.25, 'i_offset': 0.0, 'tau_m': 20.0,
                   'tau_refrac': 2.0, 'tau_syn_E': 5.0, 'tau_syn_I': 5.0,
                   'v_reset': -70.0, 'v_rest': -65.0, 'v_thresh': -50.0}
p.setup()
p1 = p.Population(5, p.IF_curr_exp(**CELL_PARAMS_LIF), label='pop_1')
p1.set(tau_m=20.0)

error:
TypeError: set() got an unexpected keyword argument 'tau_m'

other standard names such as set(cm=0.2) also fail

**Comment by Christian-B** [comment]
All pynn7 format
p1.set('cm', 0.2)

Does work.

**Comment by Christian-B** [comment]
suggested fix is to use Alan's favorite python think kwargs

    #@overrides(PyNNPopulationCommon.set)
    def set(self, **kwargs):
        for parameter, value in kwargs.iteritems():
            try:
                PyNNPopulationCommon.set(self, parameter, value)
            except InvalidParameterType:
                self.initialize(parameter, value)

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/15

**Comment by alan-stokes** [comment]
;(
