### ISSUE TITLE
ProvenanceWhenNotStartedTest test broken

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#143]
/sPyNNaker8/p8_integration_tests/test_provenance/test_provenance_when_not_started.py

Now raises a different exception to the past.

tested on bleeding edge branch including speed_up_data_in

Weird test so Alan can get it to run out of DTCM again

**Comment by Christian-B** [comment]
I think it only applies for https://github.com/SpiNNakerManchester/sPyNNaker8/pull/123

**Comment by alan-stokes** [comment]
i guess this goes under donals remit now. given hes bringing this stuff up to date

**Comment by andrewgait** [comment]
Looks like this test didn't make the cut in the recent upgrade of the integration tests.  Do we have any plans to reintroduce it in some form?

**Comment by Christian-B** [comment]
"Not I" said the Duck

**Comment by rowleya** [comment]
Closing - reopen if this is supposed to test anything in particular (but it sounds more like a development test)
