### ISSUE TITLE
Version check fails in spynnaker8/setup_pynn.py

### ISSUE THREAD

**Issue by uahic** [SpiNNakerManchester/sPyNNaker8#161]
The install script spynnaker8/setup_pynn.py fails with  PyNN 0.9.0 as the comparison implemented in 'version_satisfies' compares only greater than but I think it should be greater-equal as follows:

`    return Version(module.__version__) >= Version(requirement)
`

**Comment by andrewgait** [comment]
Thanks @uahic for noticing this and suggesting the fix.
