### ISSUE TITLE
splitting simulations into multiple runs causes strange behaviour

### ISSUE THREAD

**Issue by rjames91** [SpiNNakerManchester/sPyNNaker8#165]
I'm not sure if this is a sPyNNaker8 issue but...

When trying to run a simulation as split runs (e.g. run(500.) run(500.)) I'm getting some odd behaviour after the simulation resumes (during the second run(500.))

I've made a simple test (https://github.com/SpiNNakerManchester/PyNN8Examples/blob/rob_testing/examples/split_runs.py) to produce this error. It feels like it's possible something going wrong with auto pause resume functionality?

I only want to run simulations like this to monitor plastic connection weights changing over time. Is this still the correct way to go about doing this?

Thanks,
Rob

**Comment by andrewgait** [comment]
Hi Rob,

I was seeing something similar to this earlier this afternoon as well - I think the recent merges into master have caused this issue in some way, and it definitely seems to be the auto-pause resume functionality that’s broken.  I was seeing it on the balanced_random script in IntroLab, which also does multiple runs; I’m not completely sure, but I think that @rowleya found something like this earlier this week as well... ?

**Comment by andrewgait** [comment]
Hi Rob, I think this has been fixed now by https://github.com/SpiNNakerManchester/sPyNNaker/pull/547 (and merged into master), so please try again, especially with anything with plastic connections...

**Comment by Christian-B** [comment]
No report for a long time after a possible fix.

Assuming fixed.
