### ISSUE TITLE
Recreate network topology

### ISSUE THREAD

**Issue by ChiaraBartolozzi** [SpiNNakerManchester/sPyNNaker8#168]
Put numbers on the connections and understand which type of connections are used between different types of neurons

**Comment by rowleya** [comment]
One interesting thing I saw here was static connections with w=0.  Does this mean weight = 0?

**Comment by ChiaraBartolozzi** [comment]
right! these are the teaching signals, they do not provoke any effect on the postsynaptic neuron, but they trigger the learning
