### ISSUE TITLE
SpinnakerLink1PopTest test not working.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#189]
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_fga_tests/test_spinnaker_link_connectors/test_spinnaker_link_1pop.py

Fixed issue that p.Population should be given None instead of 2000
(part of Jenkin prs so fix by hand here)

On 4 chip board board
spinnman.exceptions.SpinnmanTimeoutException: Operation waiting for cores (0, 0) to reach one of [<CPUState.READY: 5>] timed out after 5 seconds

The extra monitor on 0, 0 has detected that 612009 packets were dumped from a outgoing link of this chip's router. This often occurs when external devices are used in the script but not connected to the communication fabric correctly. These packets may have been reinjected multiple times and so this number may be a overestimate.

If this is normal the tests should be commented to sya when they would work!

**Comment by andrewgait** [comment]
I think this is fixed by https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/388.

**Comment by alan-stokes** [comment]
if you dont have a device on the end, its going to pour packets over and over coz of the reinjector

**Comment by andrewgait** [comment]
Agreed.  I think all this test is meant to do is check that the mechanism for setting up a device is working properly.

**Comment by andrewgait** [comment]
Has been fixed, please reopen if script still fails.
