### ISSUE TITLE
weight and delay retrivale from before run different shape to after run.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#22]
Doing projections[0].get(attribute_names=["delay"], format="list")
Before run (even when waiting until after run to access the data)
generates a different shape nparray to the one for the same call after run.

Looks like the array has been inverted  an possibly pushed one level down.

Same happens with delays

Changing format has No effect!

sPyNNaker8 only

Found with:
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/more_integration_tests/p8_integration_tests/tests_for_projection_param_retrieval_from_board/test_large_pop_weight_delay_retrival.py

===
I also note that the format parameter is passed to PyNNProjectionCommon.get where it is IGNORED

**Comment by Christian-B** [comment]
PyNN8 Only.

**Comment by alan-stokes** [comment]
issue is that the connection holder is dstacked during the get. As im not hot on the connection holder stuff, which si what needs to be modfiied to ahndle multiple attributes, not 1, im handing over to rowley.

**Comment by rowleya** [comment]
Possibly fixed in #36

**Comment by alan-stokes** [comment]
merged into master. integration tests say its fine now. closing
