### ISSUE TITLE
@christian fix these tests that mess with underlying stuff

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker8#278]
fix tests in 
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/unittests/test_pop_views_assembly/test_getting.py#L65-L266

**Comment by Christian-B** [comment]
could not replicate any problems with https://github.com/SpiNNakerManchester/sPyNNaker8/blob/cherry_pick_time_steps/unittests/test_pop_views_assembly/test_getting.py
Have removed the skip and if the test pass will close.

**Comment by Christian-B** [comment]
if the issue is that the test mock in pop._get_spikes and pop._get_recorded_matrix then the reply is YES the DO and YES they NEED TOO!

**Comment by Christian-B** [comment]
Unit test pass and test what they where designed to test!

So there is no issue to address here!

**Comment by alan-stokes** [comment]
if they work now. i must have fixed something when adjusting for my set of tests for calling get data before running.  but my issue with these tests are how they fudge the ASB internals just to allow it to generate a neo object. But i guess ive fixed it going down to the problem area in a different way now

**Comment by Christian-B** [comment]
These tests do not "fudge" with ASB in fact they dont change ASB at all.

The duck type in replacement methods for
RecordingCommon._get_spikes 
RecordingCommon._get_recorded_matrix 

This is required for unit testing as clearly RecordingCommon can not return data without running.

And the test where to see how a view gets a subset of the total data.

**Comment by alan-stokes** [comment]
get_simulator().get_current_time = mock_time

hog wash they dont "fudge" with ASB. that line is in every test and changes the way the ASB would return the time. its pretending the thing ran for gods sake. that is a fudge.

**Comment by Christian-B** [comment]
"its pretending the thing ran"  yep! That is exactly what the test is designed to do.

**Comment by alan-stokes** [comment]
then why not move it into intergration tests and actually run it. by faking the run. any objects that are needed by a run you need to fake as well. which is just opening a can of worms.

**Comment by Christian-B** [comment]
Because it is testing JUST the part of splitting the received results by VIEW!

Making them integration tests 
1. Slows them down
2. Makes them more complicated
3. Make them more susceptible other changes

So Just NO! 

It is completely acceptable for unit tests to MOCK in the part that are not being tested. That keeps everything else both simple and constant!

**Comment by alan-stokes** [comment]
ba humbug. *throws pie at the wall and sits in a huff*
