### ISSUE TITLE
Does get_data have annotations?

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker8#288]
On `Population.get_data`, there's an additional `annotations` parameter (relative to `PopulationBase`. Should this also be on the base class and on `PopulationView`? Or is this something where the population just fundamentally varies from the views over it? (That would be odd for PyNN…)

(Found as part of #287.)

**Comment by Christian-B** [comment]
Looking at:
http://neuralensemble.org/docs/PyNN/reference/populations.html
 It is UGLY!!!!!


Populations.get_data(variables='all', gather=True, clear=False)
Views.get_data(variables='all', gather=True, clear=False)
BUT!
Assemblies.get_data(variables='all', gather=True, clear=False, annotations=None)
All write_data(io, variables='all', gather=True, clear=False, annotations=None)

**Comment by Christian-B** [comment]
PyNN has a different way of getting data for write_data vs get_data.
We have the same method!
So We will just have annotations on all methods that provide data!

**Comment by Christian-B** [comment]
Addressed in https://github.com/SpiNNakerManchester/sPyNNaker8/pull/291
No idea WHY users would want to add WHAT annotations but as we know how to let them why not.

**Comment by Christian-B** [comment]
fixed as much as PyNN allows
