### ISSUE TITLE
Bad code in Spynnaker8FailedState

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker8#289]
`Spynnaker8FailedState.get_generated_output()` (in `spynnaker8/spinnaker.py`) calls a function that does not exist. What should be done about this? 

I'd be happy with “delete” or “make it work like the other methods in that class” but if you have better ideas for fixing then that's good too.

(Found as part of #287)

**Comment by dkfellows** [comment]
Accidentally committed when it really belongs on another branch? OK. I hope to see the rest of the branch make it in sometime…

**Comment by rowleya** [comment]
Fixed by deletion
