### ISSUE TITLE
Ugly hidden inheritance requirement

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker8#290]
`spynnaker8.models.recorder.Recorder` can only work if the class is also a `spynnaker.pyNN.models.pynn_population_common.PyNNPopulationCommon` because it assumes that there is an `_all_ids` field and that's the only class that ever defines one. This is ugly. Something neater should be done, but I'm not sure what.

(Found as part of #287.)

**Comment by Christian-B** [comment]
Looking at it Population has two superclasses and implements one interface

The Interface is PopulationBase is shared with PopulationView and would be shared with Assembliy so it fine.

The Two Superclasses are:
PyNNPopulationCommon and Recorder where Recorder extends RecordingCommon
Population is the ONLY thing that uses these three superlcasses

The line count is:
Population 462  (spynnaker8)
PyNNPopulationCommon 584  (spynakker)
Recorder 466 (spynakker8)
RecordingCommon 262 (spynakker)

There is a lot of spaghetti left over from the PyNN7 vs Pynn8 monster.
 
Suggestion merge into 1 big class.
Then if too big split off some to a super class.

@dkfellows @rowleya @alan-stokes @andrewgait Opinions?

**Comment by rowleya** [comment]
Sounds like it is being made more confusing by separation.  I suggest merging.

**Comment by dkfellows** [comment]
Is there likely to be other directly-recordable things?

**Comment by andrewgait** [comment]
No objections to merging all of them but it might be easier to start off with to merge the sPyNNaker8 classes and sPyNNaker classes separately.  Then at some point we can look at merging all of sPyNNaker8 into sPyNNaker... ?

**Comment by Christian-B** [comment]
This work is messy to do without first moving.merging the sPyNNaker8 code into sPyNNaker

**Comment by Christian-B** [comment]
At a minimum to merge these we should move
Population which then requires moving
IDMixin, PopulationBase, PopulationView, DataCache, VariableCache, Recorder

**Comment by Christian-B** [comment]
Fixed in https://github.com/SpiNNakerManchester/sPyNNaker/pull/958
