### ISSUE TITLE
make tests put their report folders in a cental place

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker8#309]
trying to debug stuff when it only fails on Jenkins is a pain in the arse. 

one of the issues is that the reports are often next to the test. which means traversing folders just to get to the actual reports for debugging. 

We have a flag in the cfg for controlling the location of the reports folder. Why cant we have a cfg file at the top level of the integration tests which states the reports should be at the top level, and have the tools read it and use accordingly?

a second view would be to take the run_safe method to actually call setup, which would then be able to adjust the config accordingly. This would require all tests to not do setup. which im not keen on

my other view is that cfg file that jenkins loads should have the report folder etc set to the folder of p8_intergration_tests which would then mean all defaulted fodlers would go there without any changes. this would then require any dodgy test that ASSUMED it was going to be local to tis file, can add its own cfg demanding its located next to it (or be adjusted to find it from p8_intergration_tests. 

but tranversing many locations for each test just to get to the debug reports seems overwork that can be avoided

**Comment by Christian-B** [comment]
To the best of my knowledge there are NO test that assume anything about the location of the reports folder.

The iobuf and debug_mode tests use methods to get the folder locations. So @alan-stokes which are these so called " dodgy test"

**Comment by Christian-B** [comment]
It would be easy enough to have a central report folder.
But then there would be several hundred directories only distinguishable by timestamp.

I think this would make debugging harder not easier.

Suggest closing as will not fix.
