### ISSUE TITLE
Selective recording warning activates when selective recording isn't turned on

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNaker8#310]
Just a minor thing I've been noticing recently - if you record signals (not spikes) on more than one population, then warnings about selective recording are given even if selective recording isn't turned on.

Script:

```
import spynnaker8 as sim

sim.setup(timestep=1.0)

pop1 = sim.Population(1, sim.IF_curr_exp, label="pop1")
pop2 = sim.Population(1, sim.IF_curr_exp, label="pop2")

pop1.record('v')
pop2.record('v')
sim.run(1)

v1 = pop1.get_data('v')
v2 = pop2.get_data('v')

sim.end()
```

results in

2019-11-21 14:58:23 WARNING: Warning getting data on a whole population when selective recording is active will result in only the requested neurons being returned in numerical order and without repeats.

when selective recording definitely hasn't been turned on.

**Comment by andrewgait** [comment]
Suggested edit: spynnaker8/models/recorder.py line 387, just compare the length of the arrays rather than the arrays themselves; not sure whether there's anything more subtle going on, though...

**Comment by alan-stokes** [comment]
in the little time i spent last night on this. it LOOKS like there's a confusion over the pynn global neuron id for the given neuron in each pop. which when i tried to chase down, i couldn't figure it out. so it might be indicative of a worse issue.

**Comment by Christian-B** [comment]
Both @andrewgait and @alan-stokes where spot on.

Fixed in https://github.com/SpiNNakerManchester/sPyNNaker8/pull/312
