### ISSUE TITLE
'module' object has no attribute 'StructuralMechanism'

### ISSUE THREAD

**Issue by meltingCat** [SpiNNakerManchester/sPyNNaker8#335]
hi, how to solve those problems?
using spynnaker7 branch "structural_plasticity"

i would like to run the code from https://data.mendeley.com/datasets/84pvnm3rj3/1

```
>>> import spynnaker7.pyNN as sim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "spynnaker7/pyNN/__init__.py", line 35, in <module>
    from spynnaker.pyNN.models.neuron.synapse_dynamics.synapse_dynamics_structural \
ImportError: No module named synapse_dynamics_structural
```

```
>>> import spynnaker7 as sim
>>> sim.StructuralMechanism()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'StructuralMechanism'
```

**Comment by alan-stokes** [comment]
spynnaker7 and structural plasticity are not a combination that we support. If you wish to use Structural plasticity, you will need to move to spynnaker8 (aka pynn 0.8 /0.9) if you check out our spynnaker7 repo, its basically been obsoleted. https://github.com/SpiNNakerManchester/sPyNNaker7
