### ISSUE TITLE
Remove pyNN 0.8 and neo 0.4 support

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#344]
We currently still support pyNN0.8 and neo 0.4 
This is based on the test in 
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/spynnaker8/utilities/version_util.py

@apdavison If I am correct see no reason to support this version and suggests everyone moves to pyNN 0.9 and neo 0.5

I suggest we strip this out rather than move it to https://github.com/SpiNNakerManchester/sPyNNaker as required for https://github.com/SpiNNakerManchester/sPyNNaker8/issues/290

**Comment by apdavison** [comment]
I support dropping support for PyNN 0.8 and Neo 0.4.

The current version of Neo is 0.8; it would be good to support that, and drop support for previous versions.
