### ISSUE TITLE
Quantities 12.1 and numpy13

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#53]
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/setup.py

https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/requirements.txt

Need updating

Should

**Comment by rowleya** [comment]
I think setup.py has been done (it talks about quantities 12.0).  requirements.txt should probably be updated...

**Comment by Christian-B** [comment]
setup.py still has
    dependency_links=['http://github.com/python-quantities/python-quantities/'
                      'tarball/master#egg=quantities'],

so needs fixing

**Comment by rowleya** [comment]
Fair enough - missed than one!

**Comment by Christian-B** [comment]
fixed in https://github.com/SpiNNakerManchester/sPyNNaker8/pull/54

Also need to do newmodel templates so keep up until that is done and merged too

**Comment by Christian-B** [comment]
Second attempt at fix in: https://github.com/SpiNNakerManchester/sPyNNaker8/pull/55

**Comment by Christian-B** [comment]
Also https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/6

**Comment by rowleya** [comment]
Merged and tested
