### ISSUE TITLE
PyNN 

### ISSUE THREAD

**Issue by Hadeel-jarad** [SpiNNakerManchester/sPyNNaker8#541]
when I tried to install  sPyNNaker8 package (pip install sPyNNaker8) using the terminal of visual studio code on win10 I get this error :

ERROR: The tar file (C:\Users\j82884ha\AppData\Local\Temp\pip-unpack-7hgibrzu\PyNN-0.9.5.tar.gz) has a file (C:\Users\j82884ha\AppData\Local\Temp\pip-install-a5x1w2f0\pynn_06467e81891841f0a94010ebb565ed0d\pyNN/hardware/aux.py) trying to install outside target directory (C:\Users\j82884ha\AppData\Local\Temp\pip-install-a5x1w2f0\pynn_06467e81891841f0a94010ebb565ed0d)

any help to solve it

**Comment by Christian-B** [comment]
As shown in the readme this repository is no longer in use and is unsupported.

Please use:
https://github.com/SpiNNakerManchester/sPyNNaker

See:
https://spinnakermanchester.github.io/
for more information.
