### ISSUE TITLE
Population backward compatability broken

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#6]
.../sPyNNaker8/spynnaker8/models/populations/population.py 

def __init__(...
   ...
   elif issubclass(cellclass, DataHolder):
   ...
   internal_params['n_neurons'] = size
   vertex_holder = cellclass(**internal_params)

TypeError: __init__() got an unexpected keyword argument 'n_neurons'

====
Replicate:
    p.setup()
    p.Population(10, p.SpikeSourceArray,{'spike_times':  [100, 200]}, label='messed up')

====
Also other cellclass throw same error

Example
    p.setup(timestep=0.04, min_delay=1.0, max_delay=4.0)
    cell_params_lif = {....
    p.Population(10, p.IF_cond_exp, cell_params_lif, label='pop_1')

**Comment by alan-stokes** [comment]
fixed in pull request #7
