### ISSUE TITLE
Spike io test failing

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#83]
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/test_various/test_spike_io_multi_run.py

Fails with
  Received exception class: SpinnmanTimeoutException 
     With message: Operation SDP_RUNNING_MESSAGE_ID_CODES.SDP_CLEAR_IOBUF_CODE timed out after 0.5 second

**Comment by alan-stokes** [comment]
ah......... wait till mc_vs_fr_safety is merged........ i may have missed a wee fix which i noticed in there during the merges with master

**Comment by alan-stokes** [comment]
works now. closing
