### ISSUE TITLE
SpikeSourceArray object has no attribute 'describe'

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#9]
p.setup(timestep=1, min_delay=1, max_delay=15)

    population = p.Population(1, p.SpikeSourceArray(spike_times=[[0]]),
                            label='inputSSA_1')

    population.record("all")

    p.run(30)

**Comment by alan-stokes** [comment]
in pull request https://github.com/SpiNNakerManchester/sPyNNaker/pull/321

**Comment by Christian-B** [comment]
AttributeError: 'SpikeSourcePoisson' object has no attribute 'describe'

Any other that slipped??

**Comment by alan-stokes** [comment]
fixed https://github.com/SpiNNakerManchester/sPyNNaker/pull/322

**Comment by alan-stokes** [comment]
looks like this can be closed now
