### ISSUE TITLE
Adding a new population after run fails

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker8#94]
Script:

import spynnaker8 as sim
sim.setup(timestep=1)
pop_1 = sim.Population(5, sim.IF_curr_exp(), label="pop_1")
simtime = 10
sim.run(simtime)
sim.reset()
pop_2 = sim.Population(5, sim.IF_curr_exp(), label="pop_2")
sim.run(simtime)
sim.end()

On a spin3 board gives:
    iptag.port = self._connection.local_port
  File ".../SpiNNMachine/spinn_machine/tags/abstract_tag.py", line 42, in port
    raise RuntimeError("Port cannot be set more than once")
RuntimeError: Port cannot be set more than once

With spalloc you get:
  File ".../PACMAN/pacman/utilities/utility_objs/resource_tracker.py", line 373, in _get_usable_chips
    "No valid chips found on the specified board")
pacman.exceptions.PacmanInvalidParameterException: ('chips and board_address', '[(1, 0)] and None', 'No valid chips found on the specified board')

or with fix2
  File ".../PACMAN/pacman/operations/fixed_route_router/fixed_route_router.py", line 169, in _do_dynamic_routing
    "fixed route entry", str(key))
pacman.exceptions.PacmanAlreadyExistsException: ('fixed route entry', '(8, 8)')

**Comment by alan-stokes** [comment]
On a spin3 board gives:
iptag.port = self._connection.local_port
File ".../SpiNNMachine/spinn_machine/tags/abstract_tag.py", line 42, in port
raise RuntimeError("Port cannot be set more than once")
RuntimeError: Port cannot be set more than once

that'll be fixed in fix2 as it currently stands

spalloc i cant test, nor a spinn3 board.

**Comment by Christian-B** [comment]
Tested on both spin3 and spalloc and could not repelicate so assuming fixed.
