### ISSUE TITLE
Population object has no attribute 'first_id'

### ISSUE THREAD

**Issue by apdavison** [SpiNNakerManchester/sPyNNaker8#98]
which PyNN expects.

It does have '_first_id', however.

**Comment by alan-stokes** [comment]
not true in master version. The Spynnaker 8 pop inherits from the spynnaker pop where all common code resides. That indeed has a property first_id. 

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/pynn_population_common.py#L85-L87

closing, your welcome to reopen if found to be incorrect.

**Comment by apdavison** [comment]
So then master has not yet been deployed to the NMPI system, I guess.

**Comment by alan-stokes** [comment]
not yet, we're getting close to a release though. we've been debating having a release for the last month. The last few days of commits are attempts to solidify the tools for being released.

**Comment by alan-stokes** [comment]
does raise the question about getting NMPI to be able to run master when requested *looks at rowley*

**Comment by rowleya** [comment]
It should be an option - not finished that branch yet though...
